# Generated by Django 4.2.3 on 2023-07-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
